### ISSUE TITLE
再放送の番組が返却されない

### ISSUE THREAD

**Issue by takonasu** [sun-yryr/agqr-program-guide#14]
v1において，
https://agqr.sun-yryr.com/api/all
や
https://agqr.sun-yryr.com/api/today
を実行した場合，再放送の番組が表示されません．
仕様なのかを把握できなかったのでIssueを建てさせてもらいました．
よろしくお願いします．

**Comment by sun-yryr** [comment]
連絡ありがとうございます！

デフォルトで再放送は省いているので、クエリパラメータで `isRepeat=true` を指定していただければ取得できるようになります。
`https://agqr.sun-yryr.com/api/all?isRepeat=true` になります。

Swaggerへの記述が漏れてたので修正しますね！

**Comment by takonasu** [comment]
ご返信ありがとうございます！
`isRepeat` パラメータが存在していたのですね，ご教授いただきありがとうございました！
